### ISSUE TITLE
pygments -> rogue

### ISSUE THREAD

**Issue by bamos** [bamos/bamos.github.io#6]
From email:

---

The page build completed successfully, but returned the following warning:

You are attempting to use the 'pygments' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml'. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:

  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

If you have any questions you can contact us by replying to this email.

**Comment by wesleifreitas** [comment]
GitHub has recently changed gh-pages, it looks like syntax highlighting has changed with it.

I suggest we follow the advice and switch to rouge.

**Comment by bamos** [comment]
Hi @wesleifreitas, does this change mess up the syntax highlighting on your local Jekyll instance? It did on mine when I tried it a week ago and that's why I opened this issue.

**Comment by wesleifreitas** [comment]
Hi @bamos,  

I 'm beginner in Jekyll. Already installed gem rouge ? Is it updated ?

**Comment by bamos** [comment]
Hi @wesleifreitas - the following works for me:

```
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
```

**Comment by wesleifreitas** [comment]
Very good! :)
