### ISSUE TITLE
poisson image editing link is dead on the latest post (http://bamos.github.io/2016/08/09/deep-completion/)

### ISSUE THREAD

**Issue by silky** [bamos/bamos.github.io#7]
here's a different one - http://www.ctralie.com/Teaching/PoissonImageEditing/

it's also on the ACM - http://dl.acm.org/citation.cfm?id=882269 - but not for free download.

**Comment by bamos** [comment]
Strange, the link still works for me. I've replaced it with the ACM link and also added a link to the post.

**Comment by bamos** [comment]
(And thanks!)
